const data = {
  products: [
    {
      _id: 1,
      name: 'Denim Jacket',
      slug: 'Denim-Jacket',
      category: 'Jackets',
      image: '/images/product-1.jpg',
      price: 1000,
      brand: 'Levis',
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 2,
      name: 'White Shirt',
      slug: 'White-Shirt',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 700,
      brand: 'Levis',
      rating: 4,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 3,
      name: 'Sweat Shirt',
      slug: 'Sweat-Shirt',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 1000,
      brand: 'Levis',
      rating: 4.7,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 4,
      name: 'Denim Jeans',
      slug: 'Denim-Jeans',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 1000,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 5,
      name: 'White Shawl',
      slug: 'White-Shawl',
      category: 'Shawls',
      image: '/images/product-5.jpg',
      price: 2000,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 6,
      name: 'White Shirt',
      slug: 'White-Shirt',
      category: 'Shirts',
      image: '/images/product-6.jpg',
      price: 10,
      brand: 'Levis',
      rating: 4,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 7,
      name: 'Orange Jacket',
      slug: 'Orange-Jacket',
      category: 'Jackets',
      image: '/images/product-7.jpg',
      price: 10,
      brand: 'Levis',
      rating: 4,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 8,
      name: 'Designer Jacket',
      slug: 'Designer-Jacket',
      category: 'Jackets',
      image: '/images/product-8.jpg',
      price: 10,
      brand: 'Levis',
      rating: 4,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 1,
      name: 'Hoodie',
      slug: 'Hoodie',
      category: 'Hoodies',
      image: '/images/product-9.jpg',
      price: 10,
      brand: 'Levis',
      rating: 4,
      numReviews: 10,
      countInStock: 5,
    },
  ],
};

export default data;
